sudo: required
services:
  - docker
 
before_install:
  - docker build -t jobitg/react-test -f ./client/dockerfile.dev .
   
script:
  - docker run jobitg/react-test npm run test -- --coverage

after_success:
  - docker build -t jobitg/multi-client ./client
  - docker build -t jobitg/multi-nginx ./nginx
  - docker build -t jobitg/multi-server ./server
  - docker build -t jobitg/multi-worker ./worker    
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jobitg/multi-client
  - docker push jobitg/multi-nginx
  - docker push jobitg/multi-server
  - docker push jobitg/multi-worker

